name: CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/cpp-build-in-container.yml
