name: CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-reusable:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/cpp-build-in-container.yml
    with:
      build_types: "['Debug', 'Release']"
      compilers: "['g++-13', 'clang++-15']"
